
- name: create interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    mode: 0644
    owner: root
    group: root

- name: enable networking service
  service:
    name: networking
    enabled: yes
