
- name: create ntp configuration
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644

- name: enable ntp
  service:
    name: chronyd
    enabled: true
