
- name: create dhcp configuration
  template:
    src: "{{ item }}.j2"
    dest: /etc/kea/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
  - "kea-ctrl-agent.conf"
  - "kea-dhcp-ddns.conf"
  - "kea-dhcp4.conf"
  - "kea-dhcp6.conf"

- name: enable dhcp
  service:
    name: kea-dhcp4-server
    enabled: true
  
