
- name: create router advertisement configuration when ipv6 is enabled
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
    mode: 0644
    owner: root
    group: root
  when: ipv6 is defined

- name: enable router advertisement when ipv6 is enabled
  service:
    name: radvd
    enabled: true
  when: ipv6 is defined

- name: delete router advertisement configuration when ipv6 is disabled
  file:
    path: /etc/radvd.conf
    state: absent
  when: ipv6 is not defined

- name: disable router advertisement when ipv6 is disabled
  service:
    name: radvd
    enabled: false
  when: ipv6 is not defined


