
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - pppoe
    - kea
    - unbound
    - chrony
    - radvd
    - tcpdump
    - dnsutils
    - strongswan
    - xl2tpd
    - wide-dhcpv6-client
